### PR TITLE
code

### PR DESCRIPTION
**Pull request by oleksandr-gotin**

### CODE REVIEW

**Comment by kozhukhovsky** [comment]
Why did you remove the class with tests?

**Comment by oleksandr-gotin** [comment]
> Why did you remove the class with tests?

I thought it was overkill to include it. Previously, mentors always asked: why do you include a class with tests in a commit.

**Comment by kozhukhovsky** [comment]
There were tests in the beginning. They should not be changed, respectively, they will not get into the commit, but will initially be in the branch. If you delete the test, then Travis will not be able to check the functionality of the code and the test will pass anyway.

**Review by kozhukhovsky — CHANGES_REQUESTED** [review]
Add test class to repo

**Comment by oleksandr-gotin** [comment]
> Add test class to repo/

I can't run the test. I get this notification

PS C:\Users\Acer\IdeaProjects\jv-pecs> git push origin pec-1
To github.com:oleksandr-gotin/jv-pecs.git
 ! [rejected]        pec-1 -> pec-1 (fetch first)
error: failed to push some refs to 'github.com:oleksandr-gotin/jv-pecs.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Pull request closed without merging**
